name: uci-spambase
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip
  - graphviz
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - scikit-learn
  - statsmodels
